### ISSUE TITLE
OPLL Volume setting doesn't work for all channels it seems

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/libkss#1]
My implementation of libkss has a function:

```
int crSetVolumes(void *context, int sccVolume, int psgVolume, int opllVolume)
{
    kssContext *kss = (kssContext*)context;
    KSSPLAY_set_device_volume(kss->kssplay, 0, psgVolume);
    KSSPLAY_set_device_volume(kss->kssplay, 1, sccVolume);
    KSSPLAY_set_device_volume(kss->kssplay, 2, opllVolume);
    KSSPLAY_set_device_volume(kss->kssplay, 3, opllVolume);
}
```

This works fine for PSG and SCC, but for OPLL it seems some channels are being ignored. So if some FMPAC tune is playing and I change the volume some channels stay at normal volume. That's why I tried to set OPL volume as well, but that's MSX Audio, that obviously didn't work either. :)

Am I doing something wrong?

**Comment by okaxaki** [comment]
This code seems correct. I tested again the KSSPLAY_set_device_volume in kss2wav.c like following and it worked fine.

```
// from kss2wav.c
...
  /* INIT KSSPLAY */
  kssplay = KSSPLAY_new(rate, nch, bps);
  KSSPLAY_set_data(kssplay, kss);
  KSSPLAY_reset(kssplay, song_num, 0);

  KSSPLAY_set_device_quality(kssplay, EDSC_PSG, quality);
  KSSPLAY_set_device_quality(kssplay, EDSC_SCC, quality);
  KSSPLAY_set_device_quality(kssplay, EDSC_OPLL, quality);
  KSSPLAY_set_device_volume(kssplay, EDSC_OPLL, 32);
...
```

Please make sure again that the variable `opllVolume` contains a correct value.

**Comment by niekvlessert** [comment]
Hmm, it seems this is my mistake, I tried some more with the music from Xak, and I found that in the tune having the issue the PSG is very soft, so I can still hear the FMPAC even if the volume is way down. So excuse me!
