### ISSUE TITLE
VGM exporter

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/libkss#4]
Maybe it would be nice to have a VGM exporter in Libkss. It could function similar to the way OpenMSX does things using a TCL script; by writing all data the emulated audio registers receive to disk. Here's a link to the [script](https://bitbucket.org/grauw/vgmplay-msx/src/tip/tools/vgmrec.tcl?at=default&fileviewer=file-view-default) and [some info](https://vgmrips.net/forum/viewtopic.php?t=1993&p=7314).

**Comment by okaxaki** [comment]
I also think it is nice so I label this issue as enhancement. I know how to implement the feature but I have not implemented it for several years, because i'm very  very lazy person... sorry...

**Comment by okaxaki** [comment]
I've started to implement such an exporter as [KSS2VGM](https://github.com/digital-sound-antiques/kss2vgm).

**Comment by okaxaki** [comment]
The [kss2vgm](https://github.com/digital-sound-antiques/kss2vgm) 0.1.1 was released so I close this issue.
