### ISSUE TITLE
PSG emulation could be improved

### ISSUE THREAD

**Issue by oh-ren** [digital-sound-antiques/libkss#5]
First off: very cool you moved your stuff to Github, and still are actively working on this, much appreciated! :sunglasses:

There are some PSG tunes that not quite sound as they should, having some distortion & crackles, e.g:
#### Vampire Killer
- Out of Time
- Wicked Child
- Game Over
#### Penguin Adventure
- Shop 3 - Angry Fisher
- Cold Ocean
- ??? (short tune with bells as in 'The Map')

**Comment by okaxaki** [comment]
Thank you for your report. I'd like to check whether they are song-specific problems or not. If there's some general distortion problem with high frequency tone, it may be aliasing noise. The "emulate PSG at real clock" option (can be set on in_msx.dll) may improve the problem.

**Comment by oh-ren** [comment]
_emulate PSG at real clock_ doesn't make a change.
In both cases it seems like it's the _(hi-)hats_ that cause this distortion or they just seem to be completely missing (e.g. VK's _Walking on the Edge_.)
NEZplug & Game_Emu_Player seem to playback these fine.

**Comment by okaxaki** [comment]
Hi I confirmed that it's a bug of emu2149 module. I've fixed the emu2149 and applied to libkss.
I will update the other applications (ex. MSXplug and MSXplay.js) later. Thank you for your kind reporting!

**Comment by okaxaki** [comment]
I have also updated in_msx repository and the new in_msx.dll is available [here](https://github.com/digital-sound-antiques/in_msx/tree/master/dist).

**Comment by oh-ren** [comment]
Cool, thanks! Interesting though this bug seemed to have gone by unnoticed for such a long time? :)

I 'studied' the fix somewhat, it seems you removed something that was put in on purpose. Since it's removed now: I wonder what the purpose of this noise/freq level check was in the first place, and couldn't this fix have adverse consequences in other situations?

**Comment by okaxaki** [comment]
Hi, the `if` clause I modified is for emulating tricky usage of PSG as a DAC. The output level of PSG is pulled-up to HIGH when it is muted. The first expression you mentioned makes output level HIGH when both noise and tone frequency equal zero. 

Of course there is a possibility of some side-effect. However, as far as I read the code again, I thought the expression was written based on my misunderstandings of PSG specification. So I dare to remove the expression.
