### ISSUE TITLE
Debugging KSS files

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/libkss#8]
We've been discussing this via Twitter direct message; your latest reaction on this was this:

How to debug KSS file is frequency asked, but there has been no good solution for the several decades. If you do not mind to some programming effort, my personal  recommendation is to trap Z80 I/O access.

I was thinking about this however; with this I still wouldn't know what is going on when the I/O is not happening and I expected it would. What about giving the option to dump all the z80 register stuff and a few lines of code from before and after to a txt file every time when a certain memory address is hit? With this setting I could compile my asm file to a kss file and check if parts of the code are reached and if so on that moment has the values in memory I expected? I could also do the I/O thing with this.

**Comment by okaxaki** [comment]
Hi,

Trapping Z80 I/O I mentioned also includes the memory I/O. Specifically, KSSPLAY_set_{iowrite,memwrite}_handler  can be used such I/O trapping.
Once we trap the I/O we can define any I/O port and can write the debug trigger command as the Z80 I/O code of the KSS. 

However, the I/O Trapping is just a part of debugging technique for CPUs, not comprehensive approach. It only makes a proper timing to dump the Z80 virtual machine internals.

To dump Z80 memory and registers, we need to snoop inside of the virtual machine itself. For this purpose, the kssplay->vm structure can be used. It contains any context of Z80 virtual machine internals (memory, register and etc.).

**Comment by okaxaki** [comment]
My intension is that the current libkss focused on providing API for debugging, not on debugger itself. 
As I mentioned above, libkss already has a minimal API for debug. So If I had time, I wanted to make such debugger as a stand-alone software like kss2vgm...
