### ISSUE TITLE
kss2wav: make it possible to output to stdout

### ISSUE THREAD

**Issue by niekvlessert** [digital-sound-antiques/libkss#9]
I would like to send the wave data into Lame straight away by using the pipe. Would be a nice feature to have. I've seen programs use the '-' sign as output filename to activate this feature, but since you can't specify the wave file name with kss2wav it might be best to add a flag.

**Comment by okaxaki** [comment]
Hi, I've added the feature. `-o-` can be used for stdout.

**Comment by niekvlessert** [comment]
Thanks for being so quick! Amazing.
